import Head from 'next/head'
import Image from 'next/image'
import {useEffect, useState} from 'react'
import AboutUs from '../components/AboutUs'
import Banner from '../components/Banner'
import Header from '../components/Header'
import Footer from '../components/Footer'
import OurServices from '../components/OurServices'

export default function Home({catResults}) {
  return (
    <div className=''>
      <Head>
        <title>All-in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header categories={catResults} />
      <Banner />
      <AboutUs />
      <OurServices categories={catResults} />

      <Footer />
    </div>
  )
}

export async function getServerSideProps() {
  try {
    const catResults = await fetch("http://127.0.0.1:8000/api/categories").
    then(res => res.json());

    return {
      props: {
        catResults,
      }
    }
  } catch(e) {
    console.log(e);
  }
}
